name: ${project.name}
main: ${package}.${package.entry}
version: ${project.version}
description: 'Safely and synchronously execute commands as a player in Folia.'
authors:
  - "tuanzisama"
api-version: "1.21"
folia-supported: true

permissions:
  "perfcmd.use":
    default: op
  "perfcmd.command.asop":
    default: op
  "perfcmd.command.asplayer":
    default: true